org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=1.21.4
loader_version=0.19.2
loom_version=1.11.8

mod_version=2.7
maven_group=pl.spectra
archives_base_name=spectra

fabric_api_version=0.119.4+1.21.4
